# Generated by Django 3.2.9 on 2021-11-28 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0010_delete_spendingtype'),
        ('budgetplanning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('budget_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='budget.category')),
            ],
        ),
    ]
