# Generated by Django 3.2.9 on 2021-11-20 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Method',
            new_name='SavingMethod',
        ),
    ]
