# Generated by Django 3.2.9 on 2021-11-21 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='budget.savingmethod'),
        ),
    ]
