# Generated by Django 3.2.9 on 2021-11-27 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_spending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spending',
            name='spendingtype',
        ),
    ]
