# Generated by Django 3.2.9 on 2021-11-27 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_remove_spending_spendingtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.CharField(choices=[('Salary', 'Salary'), ('Dividend', 'Dividend'), ('Extra', 'Extra'), ('Business', 'Business')], default=None, max_length=8)),
                ('date', models.DateField(default=datetime.date.today)),
                ('description', models.TextField()),
            ],
        ),
    ]
