# Generated by Django 3.2.9 on 2021-11-30 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0010_delete_spendingtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='spendings', to='budget.category'),
        ),
    ]
