# Generated by Django 3.2.9 on 2021-12-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0012_auto_20211204_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='creation_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
