# Generated by Django 3.2.9 on 2021-12-04 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_biography_profile_goal'),
        ('budget', '0014_budget_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Budget',
            new_name='Record',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='budget',
            new_name='record',
        ),
        migrations.RenameField(
            model_name='spending',
            old_name='budget',
            new_name='record',
        ),
    ]
