# Generated by Django 3.2.9 on 2021-12-04 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_biography_profile_goal'),
        ('budget', '0015_auto_20211204_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='income', to='budget.record'),
        ),
        migrations.AlterField(
            model_name='record',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='spending',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='spending', to='budget.category'),
        ),
        migrations.AlterField(
            model_name='spending',
            name='record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spending', to='budget.record'),
        ),
    ]
